import * as CONST from '../actions/appConstants';
let initialState = {
  page0: {
    abandon: 'to leave; to give up; to desert; to forsake; to relinquish; to surrender;',
    abate: 'to lessen; to decrease; to diminish; to subside;',
    abet: 'to help or encourage someone to do wrong or illegal deeds',
    abhor: 'to hate; to detest; to abominate; to loathe;',
    abject: 'utterly hopeless; despicable; misarable; odious; contemptible; wretched',
    abolish: 'to end officially; to annul; to nullify; to abrogate; to revoke;',
    abruptly: 'suddenly; unexpectedly;',
    absorbed: 'wholly involved or occupied; deeply interested; engrossed',
    abstain: 'to choose not to vote for or against something; to refrain;',
    abundant: 'plentiful; copious; ample; profuse; rich',
    abuse: 'to treat a person or thing wrongfully, harmfull or cruel',
    access: 'the right to enter a palce, use something, see someone',
    accessory: 'something added',
    accomplice: 'one who aids and abets a criminal',
    accomplish: 'to complete; to achieve; to fulfill',
    accost: 'to approach and speak to someone often in a hostile, aggressive, or sexually suggestive manner',
    accuse: 'to charge; to indict; to arraign',
    acknowledge: 'to admit; to accept; to recognize',
    acquire: 'to gain; to get; to obtain; to earn',
    acrid: 'unpleasantly sharp, pungent, or bitter to the taste or smell',
    acrimonious: 'full of anger, bitter feelings, and arguments; rancorous',
    acute: 'very serious or severe; sharp; keen; intense',
    // Here begins page 2
    adjacent: 'next to; close to; adjoining',
    admire: 'to respect; to esteem; to look up to; to appreciate',
    admit: 'to permit to enter; to acknowledge, often reluctantly',
    admonish: 'to warn about; to advise against doing something; to reprove gently',
    adore: 'to love greatly; to revere; to worship; to venerate',
    adroit: 'clever; smart; skillful; dextereous; deft',
    adverse: 'bad; unfavorable; harmful; negative; unpleasant',
    affable: 'pleasant; friendly, and easy to talk to',
    affluent: 'rich; wealthy; prosperous',
    aggravate: 'to make worse; to exacerbate; to complicate',
    agile: 'lively; nimble; quick; deft',
    agitate: 'to disturb; to upset; to shake; to argue (for / agains)',
    ailment: 'mild illness',
    akin: 'similar; related',
    alert: 'perceptive; quick; watchful; aware',
    alleviate: 'to lessen; to relive',
    alienate: 'to make someone stop feeling friendly or stop feeling that s/he belongs to a group',
    alloy: 'a metal made by mixing two or more different metals',
    alluring: 'attractive and exciting; enticing; tempting',
    aloof: 'reserved; indifferent',
    amateur: 'not professional; untrained',
    ambiguous: 'equivocal; doubtful; unceratin; vague; obscure',
    amicable: 'friendly; done or achieved in a polite or friendly way and without quarreling',
    ample: 'more than enough; copious; spacious; plentiful',
    // Here begins page 3
    amplify: 'to enlarge; to increase; to expand; to make stronger; to augment',
    ancestor: 'progenitor; forebear; forefather',
    anguish: 'greate sorrow; grief; torment; agonizing pain',
    ankle: 'the joint between the foot and the leg',
    antique: 'a very old and valuable object',
    applaud: 'to express approval by clapping the hands; to commend highly; to praise',
    apprisal: 'estimation; evaluation; assessment',
    appropriate: 'suitable or right for a particular situation or occasion',
    apt: 'quick to learn or understand; suitable or appropriate',
    arduous: 'demanding greate effort; strenous',
    arid: 'getting very little rain, and therefore very dry; not interesting',
    arouse: 'to spur; to incite; to provoke',
    arraign: 'to bring to court; to charge; to accuse; to indict',
    array: 'an orderly, often imposing arrangement',
    arrogance: 'haughtiness; overbearing pride or self-importance',
    aspire: 'to strive toward; to desire strongly; to seek eagerly',
    assert: 'to state or wxpress positively; to affirm; to declare; to defend or maintain',
    assiduous: 'diligent; industrious; hardworking; persevering; persistent; sedulous; thorough',
    assuage: 'to lessen; to ease; to relieve; to soothe; to alleviate; to pacify; to appease',
    astound: 'to astonish; to bewilder; to amaze; to shock; to surprise greatly',
    astray: 'away from the correct path or direction',
    audacious: 'bold; fearlessly daring; brave and shocking',
    augment: 'to increase by adding; to enlarge; to expand',
    // Here begins page 4
    avarice: 'greed; cupidity',
    aversion: 'intense dislike; repugnance; disgust',
    baffle: 'to confuse completely',
    bald: 'without hair; undisguised; plain',
    baleful: 'evil; ominous; malicious; threatening',
    ban: 'to declare that something must not be done; to prohibit or forbid officially',
    banish: 'to exile; to deport; to drive out; to send away; to expel',
    beckon: 'to signal by nodding or waving; to lure; to attract',
    bellow: 'to shout in a deep voice',
    beneficiary: 'a person who recives money or property from an insurance policy of from a will',
    bequeath: 'to leave or give by will',
    beverage: 'any drink, usually excluding water',
    bewilder: 'to confuse utterly; to baffle',
    biased: 'prejudiced',
    bicker: 'to quarrel; to argue; to squabble',
    bitter: 'very unpleasant',
    bizarre: 'very unusual and strange; odd; weird',
    blame: 'responsibility; culpability',
    blandishments: 'pleasant and persuasive words or actions',
    bleak: 'gloomy; somber; dismal; dreary; barren; bare; desolate; unsheltered; unpleasantly cold',
    blemish: 'imperfection that mars of impairs; a flaw or defect',
    blend: 'a mixture',
  },
  page1: {
    abandon: 'to leave; to give up; to desert; to forsake; to relinquish; to surrender;',
    abate: 'to lessen; to decrease; to diminish; to subside;',
    abet: 'to help or encourage someone to do wrong or illegal deeds',
    abhor: 'to hate; to detest; to abominate; to loathe;',
    abject: 'utterly hopeless; despicable; misarable; odious; contemptible; wretched',
    abolish: 'to end officially; to annul; to nullify; to abrogate; to revoke;',
    abruptly: 'suddenly; unexpectedly;',
    absorbed: 'wholly involved or occupied; deeply interested; engrossed',
    abstain: 'to choose not to vote for or against something; to refrain;',
    abundant: 'plentiful; copious; ample; profuse; rich',
    abuse: 'to treat a person or thing wrongfully, harmfull or cruel',
    access: 'the right to enter a palce, use something, see someone',
    accessory: 'something added',
    accomplice: 'one who aids and abets a criminal',
    accomplish: 'to complete; to achieve; to fulfill',
    accost: 'to approach and speak to someone often in a hostile, aggressive, or sexually suggestive manner',
    accuse: 'to charge; to indict; to arraign',
    acknowledge: 'to admit; to accept; to recognize',
    acquire: 'to gain; to get; to obtain; to earn',
    acrid: 'unpleasantly sharp, pungent, or bitter to the taste or smell',
    acrimonious: 'full of anger, bitter feelings, and arguments; rancorous',
    acute: 'very serious or severe; sharp; keen; intense',
  },
  page2: {
    adjacent: 'next to; close to; adjoining',
    admire: 'to respect; to esteem; to look up to; to appreciate',
    admit: 'to permit to enter; to acknowledge, often reluctantly',
    admonish: 'to warn about; to advise against doing something; to reprove gently',
    adore: 'to love greatly; to revere; to worship; to venerate',
    adroit: 'clever; smart; skillful; dextereous; deft',
    adverse: 'bad; unfavorable; harmful; negative; unpleasant',
    affable: 'pleasant; friendly, and easy to talk to',
    affluent: 'rich; wealthy; prosperous',
    aggravate: 'to make worse; to exacerbate; to complicate',
    agile: 'lively; nimble; quick; deft',
    agitate: 'to disturb; to upset; to shake; to argue (for / agains)',
    ailment: 'mild illness',
    akin: 'similar; related',
    alert: 'perceptive; quick; watchful; aware',
    alleviate: 'to lessen; to relive',
    alienate: 'to make someone stop feeling friendly or stop feeling that s/he belongs to a group',
    alloy: 'a metal made by mixing two or more different metals',
    alluring: 'attractive and exciting; enticing; tempting',
    aloof: 'reserved; indifferent',
    amateur: 'not professional; untrained',
    ambiguous: 'equivocal; doubtful; unceratin; vague; obscure',
    amicable: 'friendly; done or achieved in a polite or friendly way and without quarreling',
    ample: 'more than enough; copious; spacious; plentiful',
  },
  page3: {
    amplify: 'to enlarge; to increase; to expand; to make stronger; to augment',
    ancestor: 'progenitor; forebear; forefather',
    anguish: 'greate sorrow; grief; torment; agonizing pain',
    ankle: 'the joint between the foot and the leg',
    antique: 'a very old and valuable object',
    applaud: 'to express approval by clapping the hands; to commend highly; to praise',
    apprisal: 'estimation; evaluation; assessment',
    appropriate: 'suitable or right for a particular situation or occasion',
    apt: 'quick to learn or understand; suitable or appropriate',
    arduous: 'demanding greate effort; strenous',
    arid: 'getting very little rain, and therefore very dry; not interesting',
    arouse: 'to spur; to incite; to provoke',
    arraign: 'to bring to court; to charge; to accuse; to indict',
    array: 'an orderly, often imposing arrangement',
    arrogance: 'haughtiness; overbearing pride or self-importance',
    aspire: 'to strive toward; to desire strongly; to seek eagerly',
    assert: 'to state or wxpress positively; to affirm; to declare; to defend or maintain',
    assiduous: 'diligent; industrious; hardworking; persevering; persistent; sedulous; thorough',
    assuage: 'to lessen; to ease; to relieve; to soothe; to alleviate; to pacify; to appease',
    astound: 'to astonish; to bewilder; to amaze; to shock; to surprise greatly',
    astray: 'away from the correct path or direction',
    audacious: 'bold; fearlessly daring; brave and shocking',
    augment: 'to increase by adding; to enlarge; to expand',
  },
  page4: {
    avarice: 'greed; cupidity',
    aversion: 'intense dislike; repugnance; disgust',
    baffle: 'to confuse completely',
    bald: 'without hair; undisguised; plain',
    baleful: 'evil; ominous; malicious; threatening',
    ban: 'to declare that something must not be done; to prohibit or forbid officially',
    banish: 'to exile; to deport; to drive out; to send away; to expel',
    beckon: 'to signal by nodding or waving; to lure; to attract',
    bellow: 'to shout in a deep voice',
    beneficiary: 'a person who recives money or property from an insurance policy of from a will',
    bequeath: 'to leave or give by will',
    beverage: 'any drink, usually excluding water',
    bewilder: 'to confuse utterly; to baffle',
    biased: 'prejudiced',
    bicker: 'to quarrel; to argue; to squabble',
    bitter: 'very unpleasant',
    bizarre: 'very unusual and strange; odd; weird',
    blame: 'responsibility; culpability',
    blandishments: 'pleasant and persuasive words or actions',
    bleak: 'gloomy; somber; dismal; dreary; barren; bare; desolate; unsheltered; unpleasantly cold',
    blemish: 'imperfection that mars of impairs; a flaw or defect',
    blend: 'a mixture',
  },
  page5: {
    blithe: 'carefree; cheerful; lighthearted; merry; gay; joyous',
    blizzard: 'severe snowstorm; a torrent',
    blunder: 'careless or stupid mistake',
    blush: 'to become red in the face; to flush',
    boast: 'to speak with excessive pride; to brag; to swagger',
    boulder: 'a large rounded rock',
    boundary: 'a line indicating a border or limit',
    boundless: 'without limits; infinite',
    brandish: 'to shake, wave or flourish (a weapon) menacingly',
    brawl: 'a noisy fight involving a group of people, usually in a public place',
    brazen: '. insolent; impudent; audacious; brash; shameless',
    bribe: 'money or gifts given to persuade someone to do something, usually something dishonest',
    brim: 'the upper edge or rim of anything hollow; the projecting rim of a hat',
    brink: 'the edge of a high place; the verge',
    brittle: 'easily broken or damaged; fragile; frail',
    broach: 'to bring up a topic for discussion. It is often difficult to broach the subject of sex.',
    broom: 'an object used for sweeping the floor',
    brutal: 'extremely ruthless, violent, or cruel',
    bully: 'to be cruel to weaker people or animals',
    bump: 'a blow, collision, or jolt; a bulge',
    cabal: 'a secret scheme; a plot; a conspiracy; a conspiratorial group of plotters or intriguers',
    callous: 'insensitive; unfeeling; hard-hearted; emotionally hardened',
  },
  page6: {
    candid: 'open and sincere; frank; outspoken; straightforward',
    capricious: 'impulsive; unpredictable; erratic; whimsical; changeable',
    captive: 'a person who is not permitted to leave; someone who is confined',
    carve: 'to cut; to slice (meat). These beads were carved from solid ivory',
    cast: 'to throw; to pitch; to fling; to sling; to hurl',
    castigate: 'to punish; to rebuke; to reprimand; to criticize or reprove sharply',
    chaos: 'utter confusion and disorder',
    chasm: 'deep crack in the earth’s surface; an abyss or gorge; a pronounced difference; a gap',
    chaste: 'morally beyond reproach, especially in sexual thought or conduct',
    cherish: 'to treat with affection and tenderness; to treasure; to hold dear.',
    chilly: 'According to the Weather Bureau, it will be chilly tomorrow with a 50% chance of showers.',
    chore: 'a routine or minor duty, task, or job',
    cider: 'juice from apples',
    clamorous: 'loud and noisy; vociferous',
    clandestine: 'kept or done in secret, often in order to conceal an illicit or improper purpose',
    clap: 'to applaud; to strike amicably with the open hand',
    clemency: 'mercy; forgiveness; compassionate or kind treatment',
    cluttered: 'confused; jumbled; messy; littered; disorganized; untidy',
    coarse: 'rough; not smooth; not fine; not soft; crude; rude.',
    coerce: 'to compel by physical force, pressure, threat, or intimidation',
    cogent: 'convincing, persuasive',
    combat: 'to fight or struggle against; to oppose vigorously',
    commence: 'to begin; to start',
    commend: 'to praise or laud publicly or formally',
  },
  questionWord: 'abhor',
  questionAnswer1: 'lessen, decrease',
  questionAnswer2: 'hate, kill',
  questionAnswer3: 'Mother, Father',
  correctAnswer: 'hate, kill',
  answer: '',
  displayMethod: 'page0',
};

const words = (state = initialState, action) => {
  switch (action.type) {
  case CONST.GENERATE_QUESTION:
    return {
      ...state,
      questionWord: action.questionWord,
      questionAnswer1: action.questionAnswer1,
      questionAnswer2: action.questionAnswer2,
      questionAnswer3: action.questionAnswer3,
      correctAnswer: action.correctAnswer,
      answer: '',
    };
  case CONST.ANSWER:
    return {
      ...state,
      answer: action.answer,
    };
  case CONST.SELECT_PAGE:
    return {
      ...state,
      displayMethod: action.page,
    };
  default:
    return state;
  }
};
export default words;
